print(summary(airquality))
library(reshape2)
melted_data <- melt(airquality)
print(melted_data)
melted_data_id <- melt(airquality, id.vars = c("Month", "Day"))
print(melted_data_id)
cast_data <- dcast(melted_data_id, Month + Day ~ variable, mean, na.rm = TRUE)
print(cast_data)
monthly_avg <- dcast(melted_data_id, Month ~ variable, mean, na.rm = TRUE)
print(monthly_avg)
